run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - godot
    - misspell
    - noctx
    - bodyclose
    - contextcheck
    - wrapcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kiranshivaraju/loghunter
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  wrapcheck:
    ignorePackageGlobs:
      - "github.com/kiranshivaraju/loghunter/*"

issues:
  exclude-rules:
    # Allow missing godoc in test files
    - path: "_test.go"
      linters:
        - godot
    # Allow non-wrapped errors in main packages
    - path: "cmd/"
      linters:
        - wrapcheck
